---
- name: Health Check for Linux and Windows Nodes
  hosts: all
  gather_facts: true

  tasks:
    - name: Set OS family fact for easier conditioning
      set_fact:
        os_family: "{{ ansible_facts['os_family'] }}"

    # =========================
    # Resource Collection Block
    # =========================
    - name: Collect resource metrics based on OS
      block:
        # --- Linux Collection ---
        - when: os_family == "RedHat"
          block:
            - name: Get CPU usage (Linux)
              shell: top -bn1 | grep "Cpu(s)" | awk '{print 100 - $8}'
              register: linux_cpu
              changed_when: false

            - name: Get Memory usage (Linux)
              shell: free | awk '/Mem:/ {print ($3/$2) * 100}'
              register: linux_mem
              changed_when: false

            - name: Get Disk usage (Linux)
              shell: df / | awk 'NR==2 {print $5}' | sed 's/%//'
              register: linux_disk
              changed_when: false

        # --- Windows Collection ---
        - when: os_family == "Windows"
          block:
            - name: Get CPU usage (Windows)
              win_shell: |
                $cpu = Get-Counter '\Processor(_Total)\% Processor Time' | Select-Object -ExpandProperty CounterSamples
                [math]::Round($cpu.CookedValue, 2)
              register: win_cpu
              changed_when: false

            - name: Get Memory usage (Windows)
              win_shell: |
                $mem = Get-WmiObject Win32_OperatingSystem
                [math]::Round((($mem.TotalVisibleMemorySize - $mem.FreePhysicalMemory) / $mem.TotalVisibleMemorySize) * 100, 2)
              register: win_mem
              changed_when: false

            - name: Get Disk usage (Windows)
              win_shell: |
                $disk = Get-WmiObject Win32_LogicalDisk -Filter "DeviceID='C:'"
                [math]::Round((($disk.Size - $disk.FreeSpace) / $disk.Size) * 100, 2)
              register: win_disk
              changed_when: false

    # ================================
    # Set and Process Final Values
    # ================================
    - name: Unify resource values from OS-specific variables
      set_fact:
        cpu:  "{{ (os_family == 'RedHat') | ternary(linux_cpu.stdout, win_cpu.stdout) }}"
        ram:  "{{ (os_family == 'RedHat') | ternary(linux_mem.stdout, win_mem.stdout) }}"
        disk: "{{ (os_family == 'RedHat') | ternary(linux_disk.stdout, win_disk.stdout) }}"

    - name: Determine health status
      set_fact:
        # Cast to float at the moment of comparison to avoid type errors
        status: "{{ 'CRITICAL' if cpu | float > 60 or ram | float > 60 or disk | float > 60 else 'GOOD' }}"

    # ================================
    # Logging Task (Corrected)
    # ================================
    - name: Append result to a log file in /tmp on the control node
      delegate_to: localhost
      # NOTE: We write to /tmp because the 'runner' user has permission there.
      # This avoids the need for 'become' and 'sudo', which may not exist in the EE.
      lineinfile:
        path: /tmp/awx_node_health_check.log
        create: yes
        mode: '0644'
        line: "{{ inventory_hostname }} | OS: {{ os_family }} | CPU: {{ cpu | float | round(2) }}% | RAM: {{ ram | float | round(2) }}% | Disk: {{ disk | float | round(2) }}% | STATUS: {{ status }}"
