---
- name: Run System Resource Check
  hosts: DR-netTest
  become: false
  gather_facts: false

  tasks:
    - name: Execute the resource check script
      ansible.builtin.script: check_resources.sh
