---
# file: gather_sysinfo.yml
- name: Collect CPU and RAM information from localhost
  hosts: localhost
  connection: local          # run tasks on the controller itself
  gather_facts: false        # we'll gather only the facts we need

  tasks:
    - name: Gather hardware-related facts (CPU, RAM, disks, etc.)
      ansible.builtin.setup:
        gather_subset:
          - hardware
      register: hw_facts

    - name: Display the key facts in the job output
      ansible.builtin.debug:
        msg:
          cpu_model: "{{ ansible_facts['processor'][1] | default(ansible_facts['processor'][0]) }}"
          cpu_socket_count: "{{ ansible_facts['processor_count'] }}"
          cpu_core_count: "{{ ansible_facts['processor_cores'] }}"
          ram_total_mb: "{{ ansible_facts['memtotal_mb'] }}"
          ram_free_mb: "{{ ansible_facts['memfree_mb'] }}"

    - name: Save the same information to /tmp
      ansible.builtin.copy:
        dest: "/tmp/system_info_{{ inventory_hostname }}.txt"
        mode: "0644"
        content: |
          Hostname      : {{ inventory_hostname }}
          CPU model     : {{ ansible_facts['processor'][1] | default(ansible_facts['processor'][0]) }}
          CPU sockets   : {{ ansible_facts['processor_count'] }}
          CPU cores     : {{ ansible_facts['processor_cores'] }}
          RAM total (MB): {{ ansible_facts['memtotal_mb'] }}
          RAM free  (MB): {{ ansible_facts['memfree_mb'] }}
